{{ $grafanaSecret := include "trento.grafana.password" . }}

apiVersion: v1
kind: Secret
metadata:
  name: trento-server-grafana-secret
type: Opaque
data:
  admin-user: {{ "admin" | b64enc | quote }}
  admin-password: {{ $grafanaSecret | quote }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trento-web.fullname" . }}
  labels:
    {{- include "trento-web.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "trento-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "trento-web.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "trento-web.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: TRENTO_LOG_LEVEL
              value: "{{ .Values.global.logLevel }}"
            - name: TRENTO_DB_HOST
              value: "{{ .Release.Name }}-{{ .Values.global.postgresql.name }}"
            - name: TRENTO_DB_PORT
              value: "{{ .Values.global.postgresql.servicePort }}"
            - name: TRENTO_PORT
              value: "{{ .Values.webService.port }}"
            - name: TRENTO_COLLECTOR_PORT
              value: "{{ .Values.collectorService.port }}"
            - name: TRENTO_GRAFANA_PUBLIC_URL
              value: /grafana
            - name: TRENTO_GRAFANA_API_URL
              value: "http://{{ .Release.Name }}-{{ .Values.global.grafana.name }}"
            - name: TRENTO_GRAFANA_PASSWORD
              value: {{ $grafanaSecret | b64dec }}
            {{ if .Values.mTLS.enabled }}
            - name: TRENTO_ENABLE_MTLS
              value: true
            - name: TRENTO_CERT
              value: /certs/cert.pem
            - name: TRENTO_KEY
              value: /certs/cert.pem
            - name: TRENTO_CA
              value: /certs/ca.pem
            {{ end }}
            - name: TRENTO_PROMETHEUS_URL
              value: "http://{{ .Release.Name }}-{{ .Values.global.prometheus.name }}"
          args:
            - web
            - serve
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.webService.port }}
              protocol: TCP
            - name: collector
              containerPort: {{ .Values.collectorService.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/ping
              port: http
          readinessProbe:
            httpGet:
              path: /api/ping
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: certs
            mountPath: "/certs"
            readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: certs
        secret:
          secretName: {{ include "trento-web.fullname" . }}-certs
          items:
          - key: cert
            path: cert.pem
          - key: ca
            path: ca.pem
          - key: key
            path: key.pem
