basePath: /api
definitions:
  models.Check:
    properties:
      description:
        type: string
      group:
        type: string
      id:
        type: string
      implementation:
        type: string
      labels:
        type: string
      msg:
        type: string
      name:
        type: string
      premium:
        type: boolean
      remediation:
        type: string
      result:
        type: string
      selected:
        type: boolean
    type: object
  models.ClusterSettings:
    properties:
      hosts:
        items:
          $ref: '#/definitions/models.HostConnection'
        type: array
      id:
        type: string
      selected_checks:
        items:
          type: string
        type: array
    type: object
  models.HostConnection:
    properties:
      address:
        type: string
      name:
        type: string
      user:
        type: string
    type: object
  models.SAPSystemHealthSummary:
    properties:
      clusters_health:
        type: string
      database_health:
        type: string
      hosts_health:
        type: string
      id:
        type: string
      sapsystem_health:
        type: string
      sid:
        type: string
    type: object
  web.JSONCheck:
    properties:
      description:
        type: string
      group:
        type: string
      id:
        type: string
      implementation:
        type: string
      labels:
        type: string
      name:
        type: string
      premium:
        type: boolean
      remediation:
        type: string
    required:
    - group
    - id
    - name
    type: object
  web.JSONCheckResult:
    properties:
      description:
        type: string
      group:
        type: string
      hosts:
        additionalProperties:
          $ref: '#/definitions/web.JSONHosts'
        type: object
      id:
        type: string
    type: object
  web.JSONChecksGroup:
    properties:
      checks:
        items:
          $ref: '#/definitions/models.Check'
        type: array
      group:
        type: string
    type: object
  web.JSONChecksResult:
    properties:
      checks:
        additionalProperties:
          $ref: '#/definitions/web.JSONCheckResult'
        type: object
      hosts:
        additionalProperties:
          $ref: '#/definitions/web.JSONHosts'
        type: object
    required:
    - checks
    - hosts
    type: object
  web.JSONChecksSettings:
    properties:
      connection_settings:
        additionalProperties:
          type: string
        type: object
      hostnames:
        items:
          type: string
        type: array
      selected_checks:
        items:
          type: string
        type: array
    required:
    - connection_settings
    - selected_checks
    type: object
  web.JSONHosts:
    properties:
      msg:
        type: string
      reachable:
        type: boolean
      result:
        type: string
    type: object
  web.JSONTag:
    properties:
      tag:
        type: string
    required:
    - tag
    type: object
  web.Targets:
    properties:
      labels:
        additionalProperties:
          type: string
        type: object
      targets:
        items:
          type: string
        type: array
    type: object
info:
  contact:
    email: trento-project@suse.com
    name: Trento Project
    url: https://www.trento-project.io
  description: Trento API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Trento API
  version: "1.0"
paths:
  /checks/{id}/results:
    post:
      parameters:
      - description: Resource Id
        in: path
        name: id
        required: true
        type: string
      - description: Checks result
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/web.JSONChecksResult'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/web.JSONChecksResult'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a checks result entry
  /checks/{id}/settings:
    get:
      consumes:
      - application/json
      parameters:
      - description: Resource id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.JSONChecksSettings'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get the check settings
    post:
      consumes:
      - application/json
      parameters:
      - description: Resource id
        in: path
        name: id
        required: true
        type: string
      - description: Checks settings
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/web.JSONChecksSettings'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/web.JSONChecksSettings'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create the check settings
  /checks/catalog:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/web.JSONChecksGroup'
            type: array
      summary: Get the whole checks' catalog
    put:
      parameters:
      - description: Checks catalog
        in: body
        name: Body
        required: true
        schema:
          items:
            $ref: '#/definitions/web.JSONCheck'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/web.JSONCheck'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create/Updates the checks catalog
  /clusters/{cluster_id}/results:
    get:
      parameters:
      - description: Cluster Id
        in: path
        name: cluster_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a specific cluster's check results
  /clusters/{id}/tags:
    post:
      consumes:
      - application/json
      parameters:
      - description: Cluster id
        in: path
        name: id
        required: true
        type: string
      - description: The tag to create
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/web.JSONTag'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/web.JSONTag'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Add tag to Cluster
  /clusters/{id}/tags/{tag}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Cluster id
        in: path
        name: id
        required: true
        type: string
      - description: Tag
        in: path
        name: tag
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            additionalProperties: true
            type: object
      summary: Delete a specific tag that belongs to a cluster
  /clusters/settings:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ClusterSettings'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Retrieve Settings for all the clusters. Cluster's Selected checks and
        Hosts connection settings
  /databases/{id}/tags:
    post:
      consumes:
      - application/json
      parameters:
      - description: Database id
        in: path
        name: id
        required: true
        type: string
      - description: The tag to create
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/web.JSONTag'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/web.JSONTag'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Add tag to a HANA database
  /databases/{id}/tags/{tag}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Database id
        in: path
        name: id
        required: true
        type: string
      - description: Tag
        in: path
        name: tag
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            additionalProperties: true
            type: object
      summary: Delete a specific tag that belongs to a HANA database
  /hosts/{id}/tags:
    post:
      consumes:
      - application/json
      parameters:
      - description: Host id
        in: path
        name: id
        required: true
        type: string
      - description: The tag to create
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/web.JSONTag'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/web.JSONTag'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Add tag to host
  /hosts/{id}/tags/{tag}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Host id
        in: path
        name: id
        required: true
        type: string
      - description: Tag
        in: path
        name: tag
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            additionalProperties: true
            type: object
      summary: Delete a specific tag that belongs to a host
  /prometheus/targets:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/web.Targets'
            type: array
      summary: Get prometheus HTTP SD targets
  /sapsystems/{id}/tags:
    post:
      consumes:
      - application/json
      parameters:
      - description: SAPSystem id
        in: path
        name: id
        required: true
        type: string
      - description: The tag to create
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/web.JSONTag'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/web.JSONTag'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Add tag to SAPSystem
  /sapsystems/{id}/tags/{tag}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: SAPSystem id
        in: path
        name: id
        required: true
        type: string
      - description: Tag
        in: path
        name: tag
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            additionalProperties: true
            type: object
      summary: Delete a specific tag that belongs to a SAPSystem
  /sapsystems/health:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.SAPSystemHealthSummary'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Retrieve SAP Systems Health Summary
  /tags:
    get:
      consumes:
      - application/json
      parameters:
      - description: Filter by resource type
        in: query
        name: resource_type
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List all the tags in the system
schemes:
- http
swagger: "2.0"
